### ISSUE TITLE
HEAD body

### ISSUE THREAD

**Issue by blerins** [cheald/manticore#17]
Hi,

I'm getting an error from my server performing a HEAD request

    Manticore.head(url, headers: {'accept' => 'application/json'})

Server error is:

    ERROR Rack::Lint::LintError: Response body was given for HEAD request, but should be empty

Is there any way to force body to be empty?

Thanks,

Bruno.

**Comment by cheald** [comment]
This is an issue in your server code - it's returning a content body for a HEAD request. HEAD should only return headers. The error specifies "Response body was given", which suggests that the server software is returning a response body when it should not.
