### ISSUE TITLE
Logging question 

### ISSUE THREAD

**Issue by quimrstorres** [cheald/manticore#20]
Is there a way to control how requests and responses are logged? Currently everything is being sent to STDOUT and I end up with too much information there.

**Comment by cheald** [comment]
This is primarily controlled via the CommonLogging arguments passed to the JVM during startup:

    jruby -J-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog -J-Dorg.apache.commons.logging.simplelog.showdatetime=true -J-Dorg.apache.commons.logging.simplelog.log.org.apache.http=DEBUG -J-Dorg.apache.commons.logging.simplelog.log.org.apache.http.wire=ERROR your_script.rb

This will log this stuff to STDERR, so you can redirect it as you wish.

You can set up more advanced logging via a log4j config, as is described here: https://hc.apache.org/httpcomponents-client-ga/logging.html
