### ISSUE TITLE
Does keepalive require a manual setting of the 'Connection' header?

### ISSUE THREAD

**Issue by andrewvc** [cheald/manticore#24]
If I set 'keepalive' per https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L128 will the client automatically add a 'Connection: Keep-Alive' header, or must I add that manually? I'm glad to clarify in the docs if need be.

**Comment by cheald** [comment]
I don't think it does, actually. It's probably a good idea to add it on requests where keepalive is indicated, though it's not strictly necessary in HTTP/1.1.

**Comment by cheald** [comment]
Fixed via ca857e63c717aae4f91bf66f61643dd14a988ee5.
