### ISSUE TITLE
Manticore should't retry non-idempotent requests by default

### ISSUE THREAD

**Issue by sluukkonen** [cheald/manticore#25]
As seen [here](https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L163-L175), manticore currently retries all types of requests by default. To avoid any mishaps, it shouldn't retry non-idempotent requests like POST requests by default. 

According to RFC-2616, idempotent HTTP methods are GET, HEAD, PUT, DELETE, OPTIONS, and TRACE.

I'll try to whip up a patch this weekend if you aren't faster :)

**Comment by cheald** [comment]
This is true! It looks like HTTPClient already provides StandardHttpRequestRetryHandler which does exactly this. I'll get it patched and tested.

**Comment by sluukkonen** [comment]
Wow, that was fast. Thanks a lot!
