### ISSUE TITLE
Memory leak in the expired connections closing thread

### ISSUE THREAD

**Issue by sluukkonen** [cheald/manticore#26]
As seen [here](https://github.com/cheald/manticore/blob/27de266e6bcf4bb04ffec85c690ff78e5bbb1cbb/lib/manticore/client.rb#L361-L366), the thread responsible for closing expired connections is never shut down, so it holds a reference to the JRuby runtime, thus creating a memory leak. Mostly affects apps that run in a servlet container.

One possibility is do a while loop on a Java AtomicBoolean (can't really use local or instance variables, I think, since modifying them [isn't volatile](https://github.com/jruby/jruby/wiki/Concurrency-in-jruby#volatility)) instead of using `Kernel#loop`, but perhaps there is a cleaner way to accomplish this.

**Comment by cheald** [comment]
Can you elaborate a bit more on what's going on here? Ruby threads are (I believe) marked as a daemon threads, which should cause them to shut down with the main thread terminates. I don't have any experience with servlet apps, so any additional info would be useful!

**Comment by cheald** [comment]
Also, this may be obviated by HTTPComponents 4.4, which provides [setValidateAfterInactivity](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html#setValidateAfterInactivity(int)), which should be a much better solution that the current one.

**Comment by sluukkonen** [comment]
> Can you elaborate a bit more on what's going on here? Ruby threads are (I believe) marked as a daemon threads, which should cause them to shut down with the main thread terminates. 

When shutting down or replacing a JRuby app running in a servlet container (Tomcat in this case), the JVM is never killed, so the thread won't be terminated, even if it is a daemon thread.

The HttpComponents documentation contains an [example implementation](http://hc.apache.org/httpcomponents-client-4.3.x/tutorial/html/connmgmt.html#d5e405) that could be also used here. It might be a better choice, since using volatile variables is easier from Java and using `java.lang.Object#wait` instead of Ruby's sleep allows the thread to terminate immediately..

I'm not familiar with the `setValidateAfterInactivity` option, will have to investigate.

**Comment by cheald** [comment]
Aha! Okay, that makes sense. Since it's operating directly on ConnectionManager objects we shouldn't need to get JRuby involved at all. I'll get a quick patch in place.

Manticore is still currently using 4.3, so setValidateAfterInactivity isn't going to help us a lot here (yet). I'm planning on upgrading to 4.4 for the 0.5 release.

**Comment by sluukkonen** [comment]
Yeah, basically the thread responsible for cleaning up the connections just needs to be notified in an `at_exit` block that it should terminate itself. Just like how shutting down that thread pool is handled a couple of lines below.

**Comment by cheald** [comment]
Ah; if I just provide an at_exit, then, there's no real need to do the rest of it, then, as at_exit will fire with the Ruby VM is cleaned up, even if the JVM continues to run, yes?

**Comment by cheald** [comment]
Something like this _should_ fix it, I think?

Basically, a) use one monitor thread for all of Manticore, and b) clean it up `at_exit`. As I understand it, that should fix the issue by releasing the thread once the Ruby VM cleans up for exit?

```diff
diff --git a/lib/manticore/client.rb b/lib/manticore/client.rb
index 82678a2..1e0d4a9 100644
--- a/lib/manticore/client.rb
+++ b/lib/manticore/client.rb
@@ -357,17 +357,34 @@ module Manticore
         cm = pool_builder options
         cm.set_default_max_per_route options.fetch(:pool_max_per_route, @max_pool_size)
         cm.set_max_total @max_pool_size
-
-        Thread.new {
-          loop {
-            cm.closeExpiredConnections
-            sleep 5000
-          }
-        }
+        self.class.send :__monitor_pool, cm
         cm
       end
     end

+    @monitored_pools = []
+    @monitor_pool_mutex = Mutex.new
+
+    class << self
+      private
+      def __monitor_pool(pool)
+        @monitor_pool_mutex.synchronize do
+          @monitored_pools << pool
+          @pool_monitor ||= begin
+            @monitored_pool_running = true
+            t = Thread.new do
+              while @monitored_pool_running
+                @monitor_pool_mutex.synchronize { @monitored_pools.each(&:closeExpiredConnections) }
+                sleep 5000
+              end
+            end
+            at_exit { @monitored_pool_running = false; @pool_monitor.wakeup }
+            t
+          end
+        end
+      end
+    end
+
     def create_executor_if_needed
       return @executor if @executor
       @executor = Executors.new_cached_thread_pool
```

**Comment by cheald** [comment]
12cc4b036d82dc8a274306de4ef892dc13a1fe6a should fix this. Give it a shot and let me know how it works for you.

**Comment by sluukkonen** [comment]
I'll have to test that! Will be away on vacation for the next two weeks though, so it'll unfortunately have to wait.

**Comment by cheald** [comment]
No worries! Let me know how it goes, and enjoy your vacation!
