### ISSUE TITLE
Stubbing Content-Length header without body

### ISSUE THREAD

**Issue by mikeknep** [cheald/manticore#29]
I've been working on adding a Manticore adapter to WebMock, for the benefit of both myself [and others](https://github.com/bblimke/webmock/issues/454). I have all their shared adapter specs passing except for one, which attempts to stub a request and expect specific headers back but no specified body:

```ruby
it "should return response with declared headers" do
  stub_request(:get, "www.example.com").to_return(:headers => {"Content-Length" => "8888"})
  response = http_request(:get, "http://www.example.com/")
  expect(response.headers["Content-Length"]).to eq("8888")
end
```

It looks like this isn't possible in Manticore due to [this line](https://github.com/cheald/manticore/blob/ef3c352d60ca4b45b697a7a9753e2c9780e9cbf5/lib/manticore/stubbed_response.rb#L43)—a content-length header is added to a `StubbedResponse` only if a body is present, but in line 39 above, if a body is not provided it is set to an empty string. Thus the Content-Length header in the spec above will equal zero.

The Content-Length header [should be provided](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13), but is not absolutely required. Given this class is specifically for stubbing, any thoughts on removing this line? Or, can you think of any alternative(s)?

FYI, you can see my work [here](https://github.com/bblimke/webmock/compare/master...mikeknep:manticore).

**Comment by cheald** [comment]
Ah, good catch! I'm going to see if I can figure out why the body value is being defaulted. If there's a good reason for it, I'll just move it after the header setup; otherwise, I'll remove it.

**Comment by cheald** [comment]
I've elected to remove it; I think it was added with the thought that the body should always be present, even if empty, but this isn't true - things like HEAD requests may not necessarily have a body.

Thanks for the catch!

**Comment by mikeknep** [comment]
Awesome, thanks for such a quick change! Any chance you're due for a version bump sometime soon?

**Comment by cheald** [comment]
Yup, it's about time for a new release. I'll cut that today!

**Comment by mikeknep** [comment]
Sweet, sounds great. Thanks again!
