### ISSUE TITLE
Doc clarification

### ISSUE THREAD

**Issue by andrewvc** [cheald/manticore#30]
Does `#on_complete` cover both `on_success` and `on_failure`? Couldn't find that in the docs.

**Comment by cheald** [comment]
`#on_complete` should be called regardless of success or failure, yes. There may be multiple `on_complete` handlers, and they should get executed in the order that they are defined.

The general use case would be for cleaning up after a request, kind of like an ensure block. For example, something like this may be conceivably implemented:

    def run_request_with_leased_connection
      exclusive_connection = lease_storage_connection
      @client.get(url)
        .on_success {|resp| exclusive_connection.write(body: resp.body) }
        .on_complete { exclusive_connection.release }
    end

I'll update the doc to reflect this.
