### ISSUE TITLE
struct_to_name_value_pairs() sets the namespace to nil  and BasicNameValuePair doesn't seem to like that

### ISSUE THREAD

**Issue by thomas07vt** [cheald/manticore#33]
In client.rb the **struct_to_name_value_pairs** method defaults to nil, which seems to be causing issues when BasicNameValuePair is called:

```ruby
    def struct_to_name_value_pairs(value, namespace = nil)
      case value
      when nil
        []
      when Hash
        value.flat_map {|key, val| struct_to_name_value_pairs val, namespace ? "#{namespace}[#{key}]" : key }
      when Array
        value.flat_map {|val| struct_to_name_value_pairs val, namespace }
      else
        BasicNameValuePair.new(namespace, value.to_s) # <- HERE
      end
    end
```

From here:
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpcore/4.2-beta1/org/apache/http/message/BasicNameValuePair.java

it looks like BasicNameValuePair will raise an exception when a namespace is null.

When I run my code now I get this:

```bash

"Backtrace":
org.apache.http.util.Args.notNull(org/apache/http/util/Args.java:48)
org.apache.http.message.BasicNameValuePair.<init>(org/apache/http/message/BasicNameValuePair.java:58)
java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:422)
RUBY.struct_to_name_value_pairs(/home/jthomas/code/ecd/trunk/vendor/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/client.rb:535)
RUBY.uri_from_url_and_options(/home/jthomas/code/ecd/trunk/vendor/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/client.rb:416)
RUBY.request_from_options(/home/jthomas/code/ecd/trunk/vendor/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/client.rb:422)
RUBY.request(/home/jthomas/code/ecd/trunk/vendor/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/client.rb:379)
RUBY.get(/home/jthomas/code/ecd/trunk/vendor/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/client.rb:226)


```

**Comment by cheald** [comment]
It does default to nil, but `query` and `params` are expected to be instances of `Hash`, which will establish a namespace per-key in the hash. What are you passing as the query/params options?

**Comment by thomas07vt** [comment]
I was passing a string directly:
"fields=_timestamp,_source"

I can convert that to hash and see if that works.

**Comment by thomas07vt** [comment]
Yeah a hash works... which is as designed from the docs :)

 #   @option options [Hash]     query              Hash of options to be added to the URL as part of the query string
