### ISSUE TITLE
Manticore.http not defined

### ISSUE THREAD

**Issue by mikeknep** [cheald/manticore#35]
Hey @cheald,

I just added support in my [WebMock Manticore adapter](https://github.com/bblimke/webmock/pull/505) for stubbing requests made through the Manticore facade—eg. `Manticore.get(url)`. I noticed that the Manticore README suggests that you can call a generic `#http` method on Manticore, but that this method is not in fact defined on the module. The call is demonstrated in the first code example under "Quick Start".

I wasn't sure if the README was out of date and the example should be deleted, or represents intended functionality and you need to (re?)implement that method, so I'm opening an issue instead of making a PR one way or the other.

**Comment by cheald** [comment]
Ah, no, you're right! I'll get that added. The Facade just delegates to a default Client, and the http method was not correctly delegated.
