### ISSUE TITLE
Not specifying truststore_password generates an error 

### ISSUE THREAD

**Issue by andrewvc** [cheald/manticore#37]
The problem is not checking for a nil [here](https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L593)

Running with logstash and the elasticsearch output, it yields:
```
The error reported is:
  undefined method `toCharArray' for nil:NilClass
/Users/andrewvc/Downloads/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/client.rb:634:in `get_store'
```

**Comment by cheald** [comment]
Ah, I see, this can happen if you actually pass the key, but the value is nil. I'll patch it up!

**Comment by andrewvc** [comment]
Thanks @cheald :) !

**Comment by cheald** [comment]
9dce821a424baadb3b0415c3272cc8623355f72b should close this!
