### ISSUE TITLE
Manticore timeout issue

### ISSUE THREAD

**Issue by Ravikanthbk** [cheald/manticore#40]
Hi,

 I am using manticore gem for sending parallel request something like below ...

 client = Manticore::Client.new(pool_max: 10, pool_max_per_route: 10, request_timeout: 2)
 client.parallel.post('target_url', body: json_body)
 client.execute!

 But I see request timeout is not raising any Timeout exception when it reached 2 seconds.

 Is am missing anything ?

Thanks,
Ravi

**Comment by cheald** [comment]
Hi, sorry it took so long to get back to this!

Manticore will raise exceptions in handlers for each request, when operating in parallel mode. You need to attach an `on_failure` handler to the request if you want to catch and handle timeouts for the request.

```
client = Manticore::Client.new(pool_max: 10, pool_max_per_route: 10, request_timeout: 2)
client.parallel.post('target_url', body: json_body).on_failure {|e| # Handle the failure here }
client.execute!
```
