### ISSUE TITLE
Consider defaulting stale check to true

### ISSUE THREAD

**Issue by andrewvc** [cheald/manticore#43]
It appears that Manticore by default sets [DEFAULT_STALE_CHECK to false](https://github.com/cheald/manticore/blob/9acf81b2103919795a784358dea843bf0737091c/lib/manticore/client.rb#L102). This should probably be true as there are a lot of situations where this causes mysterious problems (see this logstash plugin [thread](https://github.com/logstash-plugins/logstash-output-http/issues/20#issuecomment-178504104).

Would you consider changing this @cheald ? I'd be glad to submit a patch if so.

**Comment by andrewvc** [comment]
Looking closer it seems that stale_check is now deprecated in favor of `setValidateAfterInactivity`. I'll pursue a patch along those lines. https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.html

**Comment by andrewvc** [comment]
So, I just noticed that manticore exposes this option, but sets it to a pretty high value of 15000ms. @cheald would you consider lowering this? We've seen a number of users with issues related to this value. I would up lowering it in logstash, but you might want to do it in the library as well.

**Comment by cheald** [comment]
What kinds of issues are you seeing? The check is set to 15 seconds to be conservative about the overhead imposed; stale checks aren't free, so the idea was to only impose that check if we could be reasonably certain that the connection hadn't been used recently. Is the issue that connections are becoming stale faster, and thus you're running into retries?

What sort of interval do you suggest? The actual stale-ness of a connection is going to vary based on server Keepalive values, so we can't really hit all cases with a timeout adjustment. The idea is that we should streamline stale connection pruning, without imposing every-request staleness checks.

What sorts of issues end up being exhibited? IIRC, Manticore should transparently and automatically retry a request if it was made with a stale connection - are users cycling through enough stale connections that all the retries for a request are exhausted?

**Comment by andrewvc** [comment]
@cheald well, it's tough to say what it should be. I lowered it to 200ms in Logstash to be more conservative. The thing is when a conn goes stale people get very confusing errors since they're hard to repro with curl.

See https://github.com/logstash-plugins/logstash-output-http/issues/20#issuecomment-178504104 and https://discuss.elastic.co/t/http-poller-s-weird-behavior-with-polling-urls/28620 to see examples of confused users with servers that let their keepalive silently close connections.

**Comment by andrewvc** [comment]
The apache default is 2000ms it looks like: https://github.com/apache/httpclient/blob/3c58addf11fb377c27e48e9bebc27e28e5c3a6c2/httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java#L181

**Comment by cheald** [comment]
Manticore does already expose a `:retry_non_idempotent` option, which will cause it to perform retries for POST, PUT, etc requests. It's false by default for obvious reasons.

I think we could lower the default stale check to 2000ms pretty safely (and it lets me use the "Apache does it!" defense :D), but the handling of non-idempotent requests against stale connections really has to be something handled per-app, since the acceptability of a doubled request is entirely dependent on the specific app.

**Comment by andrewvc** [comment]
@cheald yes, and we expose it in logstash too. Completely agree with the idempotence stuff as well :)

I have no idea whether 2000ms is radically better, but, hey, Apache does it! :tm:

**Comment by cheald** [comment]
Closing via 14b3fa50732522eeb1ded604d296806bbf1e6576.
