### ISSUE TITLE
Release 0.5.3?

### ISSUE THREAD

**Issue by krallin** [cheald/manticore#44]
Hey there!

I was wondering if you had any plans to release a 0.5.3 (0.5.2.1?) version with the fix included in https://github.com/cheald/manticore/commit/14b3fa50732522eeb1ded604d296806bbf1e6576?

As you probably know, Manticore is used by a large number of Logstash plugins, and it's not always possible to configure the `check_connection_timeout ` setting (in particular, the Elasticsearch output plugin doesn't appear to let you do that), so being able to rely on a better default would be extremely helpful.

Thanks!

**Comment by cheald** [comment]
Ah, I forgot to do that! Done, and thanks!

**Comment by krallin** [comment]
Thanks @cheald !
