### ISSUE TITLE
Trouble installing Manticore on JRuby 9000

### ISSUE THREAD

**Issue by fedenusy** [cheald/manticore#46]
I added the following lines to my Gemfile:

```
platform(:jruby) do
  gem 'manticore', '0.5.5'
end
```

After running `bundle`, the following line (and only this line) gets added to my Gemfile.lock:

```
...

DEPENDENCIES
  ...
  ...
  manticore (= 0.5.5)
  ...
  ...
```

I then run `rvm jruby-9.0.1.0 do bundle exec script/rails c` to open up a console. All other gems load just fine, but the `Manticore` constant is undefined. I tried `require 'manticore'` (which says "no such file to load") and `Bundler.require('manticore')` (which has no effect).

No matter what I try, the `Manticore` constant never loads. Am I missing something, or is this a bug?

**Comment by cheald** [comment]
Did you perhaps put the Manticore gem line in a group that Bundler isn't loading? It definitely works here. I just created a fresh Rails 4.2.6 app, added manticore-0.5.5 to the gemfile, bundled, booted a console, and the library is loaded as expected.

**Comment by fedenusy** [comment]
Yep, it was in a group. All other gems within that group were loading just fine though.

I tried taking manticore out of the group, and still had the same issue.

I then tried creating a fresh Rails app like the one you describe. This time I noticed a few additional lines related to manticore in the output from `bundle install`:

```
...
...
Installing jar-dependencies 0.3.2
...
...
Installing manticore 0.5.5
  jar dependencies for manticore-0.5.5-java.gemspec . . .
      org.apache.httpcomponents:httpclient:4.5:compile
      org.apache.httpcomponents:httpmime:4.5:compile
...
...
```

Whereas before I would only see:

```
...
...
Using manticore 0.5.5
...
...
```

I went back to my main app, reverted the Gemfile, ran `gem uninstall manticore`, and re-ran `bundle install manticore`. This time it worked  ¯\\_(ツ)_/¯

Feel free to close this issue. Thanks for the help!

**Comment by fedenusy** [comment]
Manticore works fine on my local machine. But now my Docker containers are having trouble installing :(

Output from `bundle install`:

```
Installing manticore 0.5.5
  jar dependencies for manticore-0.5.5-java.gemspec . . .
Warning: JAVA_HOME environment variable is not set.
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/local/rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/jars/jar_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/usr/local/rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/jars/jar_pom.rb) has 1 error
[ERROR]     Non-parseable POM /usr/local/rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/jars/jar_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

Errno::ENOENT: No such file or directory - /home/app/vendor/bundle/jruby/2.2.0/gems/manticore-0.5.5-java/deps.lst
```

I tried setting JAVA_HOME but that didn't help. JRuby 9.0.1.0, 9.0.4.0, and 9.0.5.0 all seem to spit out similar errors.

I'm digging through issues in the jar-dependencies gem. [This issue](https://github.com/mkristian/jar-dependencies/issues/25) seems like it may be related, but unfortunately nobody mentions a fix.

Any tips on how to proceed? I'll keep digging and post my solution if I find it.

**Comment by cheald** [comment]
I'm actually debugging this *exact* issue for different reasons right now. I'll let you know what I find.

**Comment by cheald** [comment]
See https://github.com/elastic/logstash/issues/4818 and https://github.com/mkristian/jar-dependencies/issues/39, specifically:

https://github.com/elastic/logstash/issues/4818#issuecomment-198266176

In the Logstash case (which is where I was debugging that issue) that XML file was missing from the ruby-maven gem directory. Re-adding it causes Manticore to install properly. You might have a similar issue here, and mkristian notes that it's broken on JRuby 9.0.5.0, as well.

**Comment by fedenusy** [comment]
`cat /usr/local/rvm/gems/jruby-9.0.1.0/gems/ruby-maven-3.3.10/.mvn/extensions.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- from ruby-maven gem -->
<extensions>
  <extension>
    <groupId>org.torquebox.mojo</groupId>
    <artifactId>mavengem-wagon</artifactId>
    <version>0.2.0</version>
  </extension>
  <extension>
    <groupId>io.takari.polyglot</groupId>
    <artifactId>polyglot-ruby</artifactId>
    <version>0.1.15</version>
  </extension>
</extensions>
```

Looks like the file is already there. Do I need to copy it into some other directory? Maybe I'm misunderstanding the solution.

**Comment by fedenusy** [comment]
On a related note, would you consider vendoring the Apache jars, similar to [jrjackson](https://github.com/guyboertje/jrjackson)? I've been using that gem for over a year with no issues.

The `jar-dependencies` approach is nice in theory, but clearly has kinks. Vendoring jars would make manticore more self-contained and future-proof.

Easier install -> bigger community -> better manticore :)

Right now the only reason I'm dealing with ruby-maven and jar-dependencies is because I *really* want to start using Manticore in production.

**Comment by fedenusy** [comment]
Mission accomplished. I'll submit a PR in case you're interested in the vendoring approach.
