### ISSUE TITLE
Support for repeatable HTTP headers 

### ISSUE THREAD

**Issue by p-b--** [cheald/manticore#57]
**Steps to replicate:**
URL: `https://httpbin.org/response-headers?Link=%3Chttps://example.com/api/status?eventcode=1234%3E;%20rel=%22next%22&Link=%3Chttps://example.com/api/status?eventcode=current%3E;%20rel=%22self%22`

```
curl -I 'https://httpbin.org/response-headers?Link=%3Chttps://example.com/api/status?eventcode=1234%3E;%20rel=%22next%22&Link=%3Chttps://example.com/api/status?eventcode=current%3E;%20rel=%22self%22'
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 21 Nov 2016 10:28:11 GMT
Content-Type: application/json
Content-Length: 228
Connection: keep-alive
Link: <https://example.com/api/status?eventcode=1234>; rel="next"
Link: <https://example.com/api/status?eventcode=current>; rel="self"
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

```

**Expected behavior:**
HTTP Headers which are allowed to be repeated are appended into the `headers` hash as per RFC 7230.

```
jruby-9.0.5.0 > response_httpbin = client.get("https://httpbin.org/response-headers?Link=%3Chttps://example.com/api/status?eventcode=1234%3E;%20rel=%22next%22&Link=%3Chttps://example.com/api/status?eventcode=current%3E;%20rel=%22self%22")
jruby-9.0.5.0 >   response_httpbin.headers
 => {"server"=>"nginx", "date"=>"Mon, 21 Nov 2016 10:36:00 GMT", "content-type"=>"application/json", "content-length"=>"228", "connection"=>"keep-alive", "link"=>"<https://example.com/api/status?eventcode=1234>; rel=\"next\", <https://example.com/api/status?eventcode=current>; rel=\"self\"", "access-control-allow-origin"=>"*", "access-control-allow-credentials"=>"true"}

```

_Relevant portion:_
`"link"=>"<https://example.com/api/status?eventcode=1234>; rel=\"next\", <https://example.com/api/status?eventcode=current>; rel=\"self\"",`

**Current Behavior:**
Headers which are allowed to be repeated are currently overwritten with the last valid HTTP header of the same name.

```
jruby-9.0.5.0 > response_httpbin = client.get("https://httpbin.org/response-headers?Link=%3Chttps://example.com/api/status?eventcode=1234%3E;%20rel=%22next%22&Link=%3Chttps://example.com/api/status?eventcode=current%3E;%20rel=%22self%22")
jruby-9.0.5.0 >   response_httpbin.headers
 => {"server"=>"nginx", "date"=>"Mon, 21 Nov 2016 10:36:00 GMT", "content-type"=>"application/json", "content-length"=>"228", "connection"=>"keep-alive", "link"=>" <https://example.com/api/status?eventcode=current>; rel=\"self\"", "access-control-allow-origin"=>"*", "access-control-allow-credentials"=>"true"}

```

_Relevant portion:_
`"link"=>"<https://example.com/api/status?eventcode=current>; rel=\"self\"",`

**Background and further notes:**
I'm working on a project which uses a Link header to paginate data (such as the Github API), however that API does not return the values as comma separated values, but rather as disparate Link headers to be built into a CSV (or whatever format desired).

While this is not the usual method of sending this data, it is not invalid per RFC 7230 [[sec3.2.2](https://tools.ietf.org/html/rfc7230#section-3.2.2)] (relevant section quoted below).

> A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma.  The order in which header fields with the same field name are received is therefore significant to the interpretation of the combined field value; a proxy MUST NOT change the order of these field values when forwarding a message.

I understand that the headers are all being placed into a hash without evaluation, overwriting one hash entry with another if there are headers of the same name.

Can you change the behavior to append the headers per the RFC specification? 

Versions of everything installed:
```
$ ruby --version
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d OpenJDK 64-Bit Server VM 25.111-b15 on 1.8.0_111-b15 +jit [linux-amd64]

$ gem list

*** LOCAL GEMS ***

...
manticore (0.6.0 java)
```

**Comment by cheald** [comment]
Yeah, this needs to be fixed. It's a relic of using Ruby's hashes for this, which have unique keys. A proper fix will be a custom class that exhibits Enumerable behavior and supports #[] to behave like a hash, but which returns multiple values when they are present.

**Comment by cheald** [comment]
Okay, I've patched this in. `Manticore::Response#[]` will still only return the first header value, but `Manticore::Response#headers` will return a hash consisting of `{header => value, header => [value1, value2]}`. So, in your example, you would use:

    Array(response.headers["link"]).each {|value| ... }

To iterate the 0-or-more values for the `Link` header.

I may make `Response#headers` eventually return a hash of `{key => [value]}` and use `Response#[]` for the quick accessor, but I'd like to evaluate the potential breakage that could be caused by doing so first.

Additionally, Client now accepts multiple headers in a similar form:

    client.get "/foo", headers: {"X-Bar": ["blaz", "bling"]}

Will now result in a request with two X-Bar headers, each with one of the given values.

**Comment by p-b--** [comment]
Great - Thanks for all the work and the turn around!
