### ISSUE TITLE
link to gitlab is dead

### ISSUE THREAD

**Issue by andreaseger** [cheald/manticore#76]
Hi,
you state in the readme that you moved this to gitlab but I can't find it on gitlab and the link in the readme only 404s.
So where is the main development going to happen? Here or on gilab?

Thanks

**Comment by cheald** [comment]
Whoops! I created the repo over there as private. That's been fixed.

**Comment by andreaseger** [comment]
thanks now it works
maybe you could also disable issues and PR here on github to make it more clear that these should be done on gitlab instead - might get confusing otherwise

**Comment by cheald** [comment]
I'm going to support issues and PRs in both places for the time being, but I'm going to make Gitlab the "canonical" endpoint, for whatever that's worth.
