### ISSUE TITLE
GitLab merge requests

### ISSUE THREAD

**Issue by davishmcclurg** [cheald/manticore#84]
I opened a merge request on gitlab, but I'm not sure if things are still maintained there. Should I open one here instead?

https://gitlab.com/cheald/manticore/merge_requests/60
https://gitlab.com/cheald/manticore/merge_requests/61

**Comment by cheald** [comment]
Oh, heh, I didn't see an email! I'll take a look. Sorry!

**Comment by davishmcclurg** [comment]
Thanks!
